# Generated by Django 4.0.4 on 2022-05-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paginas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='nome',
            field=models.CharField(max_length=256),
        ),
    ]
