# Generated by Django 4.0.4 on 2022-05-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paginas', '0002_alter_cursos_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='senha',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
