# Generated by Django 4.0.4 on 2022-05-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paginas', '0003_usuarios_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='senha',
            field=models.CharField(max_length=50),
        ),
    ]
