# Generated by Django 4.0.4 on 2022-05-04 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paginas', '0005_alter_usuarios_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/cursos_fotos'),
        ),
    ]
