# Generated by Django 4.0.4 on 2022-05-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paginas', '0006_alter_cursos_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%Y'),
        ),
    ]
