# Generated by Django 4.0.4 on 2022-05-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paginas', '0007_alter_cursos_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='video',
            field=models.FileField(blank=True, upload_to='videos/%Y'),
        ),
    ]
