# Generated by Django 4.0.4 on 2022-05-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paginas', '0008_cursos_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='video',
            field=models.FileField(upload_to='videos/%Y'),
        ),
    ]
