# Generated by Django 4.0.4 on 2022-05-13 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Paginas', '0010_categoria_remove_cursos_video_cursos_usuarioid_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='categoriaID',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='Paginas.categoria'),
        ),
    ]
