# Generated by Django 4.0.4 on 2022-05-13 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Paginas', '0012_remove_cursos_categoriaid_alter_cursos_usuarioid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoriaCurso', models.CharField(max_length=55)),
            ],
        ),
        migrations.AddField(
            model_name='cursos',
            name='categoriaID',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='Paginas.categoria'),
        ),
    ]
