# Generated by Django 4.0.4 on 2022-05-13 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Paginas', '0013_categoria_cursos_categoriaid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursos',
            name='categoriaID',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
