# Generated by Django 4.0.4 on 2022-05-21 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Paginas', '0015_categoria_cursos_categoriaid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='mostrar',
        ),
    ]
