# Generated by Django 4.0.4 on 2022-05-27 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Paginas', '0017_theme_usuarios_usertheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='userTheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Paginas.theme'),
        ),
    ]
