# Generated by Django 4.0.4 on 2022-05-27 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paginas', '0024_remove_usuarios_usertheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='teste',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
