# Generated by Django 4.0.4 on 2022-05-27 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Paginas', '0027_video_descaula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursos',
            name='horas',
        ),
    ]
