# Generated by Django 4.0.4 on 2022-05-30 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Paginas', '0029_cursosfavorito'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursosfavorito',
            name='userID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Paginas.usuarios'),
        ),
        migrations.AlterField(
            model_name='cursosfavorito',
            name='curso_ID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Paginas.cursos'),
        ),
    ]
