# Generated by Django 4.0.4 on 2022-05-30 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Paginas', '0030_cursosfavorito_userid_alter_cursosfavorito_curso_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CursosFavorito',
        ),
    ]
