# Generated by Django 4.0.4 on 2022-05-30 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Paginas', '0032_cursosfavorito'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CursosFavorito',
        ),
    ]
