# Generated by Django 4.0.4 on 2022-05-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paginas', '0035_delete_cursosfavorito'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursosFavorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuarioID', models.ManyToManyField(blank=True, to='Paginas.cursos')),
            ],
        ),
    ]
