# Generated by Django 4.0.4 on 2022-05-30 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Paginas', '0037_cursosfavor_delete_cursosfavorito'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CursosFavor',
        ),
    ]
