# Generated by Django 4.0.4 on 2022-06-05 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Paginas', '0040_alter_cursos_foto_aulaassistida'),
    ]

    operations = [
        migrations.AddField(
            model_name='aulaassistida',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Paginas.cursos'),
        ),
    ]
