# Generated by Django 4.0.4 on 2022-06-05 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Paginas', '0041_aulaassistida_curso'),
        ('Paginas', '0041_aulasassistida_curso'),
    ]

    operations = [
    ]
